name: rust_std
description: The Rust standard library implemented in Dart.
version: 0.2.1
repository: https://github.com/mcmah309/rust_std

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  universal_io: ^2.2.2
  rust_core:
  vec:
  path_type:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
