name: rust_std
description: The Rust standard library implemented in Dart.
version: 0.2.1
repository: https://github.com/mcmah309/rust_std

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  rust_core: ^1.0.0
  vec:
  path_type:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
